---
# tasks file for wordpress
- name: Download WordPress
  get_url: 
    url=https://wordpress.org/wordpress-5.1.tar.gz 
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Extract WordPress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no
  become: yes

- name: Update default Apache site
  become: yes
  lineinfile: 
    dest=/etc/apache2/sites-enabled/000-default.conf 
    regexp="(.)+DocumentRoot /var/www/html"
    line="DocumentRoot /var/www/wordpress"
  notify:
    - restart apache

- name: Copy sample config file
  command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php creates=/var/www/wordpress/wp-config.php
  become: yes

- name: Replace db username in wp-config.php
  lineinfile:
    dest: /var/www/wordpress/wp-config.php
    regexp: "(.*)username_here(.*)"
    line: '\1{{wp_mysql_user}}\2'
    backrefs: yes
  become: yes

- name: Replace db password in wp-config.php
  lineinfile:
    dest: /var/www/wordpress/wp-config.php
    regexp: "(.*)password_here(.*)"
    line: '\1{{wp_mysql_password}}\2'
    backrefs: yes

    become: yes

- name: Replace db name in wp-config.php
  lineinfile:
    dest: /var/www/wordpress/wp-config.php
    regexp: "(.*)database_name_here(.*)"
    line: '\1{{wp_mysql_db}}\2'
    backrefs: yes
  become: yes 
